Comment out failing command in the deployment step

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -227,8 +227,8 @@ jobs:
       - name: Build project
         run: npm run build
 
-      - name: Simulate deployment failure
-        run: exit 1
+      # - name: Simulate deployment failure
+      #   run: exit 1
 
       # Save build artifact for rollback use
       - uses: actions/upload-artifact@v4
@@ -245,33 +245,31 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  rollback:
+  rollback-prod-deploy:
     name: Rollback Last Successful Build
     runs-on: ubuntu-latest
-    needs: [ci, prod-deploy]
-    if: ${{ needs.ci.result == 'failure' || needs.prod-deploy.result == 'failure' }}
+    needs: prod-deploy
+    if: needs.prod-deploy.result == 'failure'
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout repo
+        uses: actions/checkout@v4
 
-      # Install GitHub CLI
       - name: Install GitHub CLI
         run: sudo apt-get update && sudo apt-get install gh -y
 
-      # Authenticate GitHub CLI
       - name: Authenticate GitHub CLI
         run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      # Download last successful artifact from prod-deploy
-      - name: Download last successful build
+      - name: Download last successful build artifact
         run: |
           LAST_RUN_ID=$(gh run list --repo ${{ github.repository }} \
             --workflow="Weather App CI/CD" \
             --status=success \
             --limit=10 \
             --json databaseId,name \
-            --jq '.[] | select(.name=="Deploy to GitHub Pages") | .databaseId' | head -n1)
+            --jq '.[] | select(.name=="Deploy to GitHub Pages (Production env)") | .databaseId' | head -n1)
 
           echo "Using last successful prod-deploy run ID: $LAST_RUN_ID"
 
@@ -280,7 +278,6 @@ jobs:
             --name static-site-public \
             --dir ./public
 
-      # Redeploy the previous build
       - name: Redeploy last successful build
         run: |
           npx gh-pages -d ./public -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
